### PR TITLE
Fixed Languages and Tools not appearing

### PR DESCRIPTION
**Pull request by CamoGekko**
Just changed the site because it moved but still all the same icons!

### CODE REVIEW

**Comment by JohnMwendwa** [comment]
Thanks for the update🤝

**Comment by JohnMwendwa** [comment]
> Just changed the site because it moved but still all the same icons!

It appears I closed this PR without merging, can you kindly open another and merge it from your end

**Comment by CamoGekko** [comment]
Will do! I can do that whenever i get to school

**Review by CamoGekko — COMMENTED** [review]
Replaces skills.thijs.gg/ with skillicons.dev/

**Pull request closed without merging**
